[package]
name = "backchannel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
backchannel-core = { path = "../../crates/backchannel-core" }
vercel_runtime = { workspace = true }
tokio = { workspace = true }
hyper = { workspace = true }
tower = { workspace = true }
axum = { workspace = true }

[[bin]]
name = "backchannel"
path = "src/main.rs"
